### ISSUE TITLE
enrichment for the /api/v3/records/services endpoint

### ISSUE THREAD

**Issue by tsoenen** [sonata-nfv/tng-gtk-sp#160]
Users of this endpoint should be able to see information about the active SLA and Policy. The useful values here are (imo):

`sla_id`
`sla_name`
`policy_id`
`policy_name`

As I see it now, `sla_id` is already there, if an sla is active. If not, the field is not there. Should we make it always present, and have it show value `null` if no sla is active?

The GK should use the sla-policy binding endpoint to find the `policy_id`

Is it up to the GK to also provide the `sla_name` and `policy_name`? Or is this the responsibility of the endpoint user, based on the provided `sla_id` and `policy_id`?

@jbonnet @mtouloup @efotopoulou @azafeiropoulos @ekapassa

**Comment by jbonnet** [comment]
Thanks, @tsoenen 

> ...The GK should use the sla-policy binding endpoint to find the policy_id...

Which endpoint is this? Which components provides it?

> ...Is it up to the GK to also provide the sla_name and policy_name? Or is this the responsibility of the endpoint user, based on the provided sla_id and policy_id?

It's simpler for the API clients for the GK to do it, as we've been doing in other endpoints (e.g., requests, where the GK delivers also the service's name, vendor and version). But this has a performance penalty, since there's at least one more call to the provider micro-services

**Comment by jbonnet** [comment]
@tsoenen is this issue still valid?

**Comment by jbonnet** [comment]
We're not going to implement this one
