### ISSUE TITLE
Improve the endpoint get /requests

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-gtk-sp#240]
When we get the first time the /request it takes around 16-18 seconds. I guess it is because of the enrichment of the reply. After the reply is cached then the reply is very quick.

**Comment by jbonnet** [comment]
Same as #224

**Comment by jbonnet** [comment]
service vendor, name and version will be added to the requests table

**Comment by jbonnet** [comment]
@felipevicens Since the problem seems to be on the very first GET request for a new service, it looks like we will have to paralelize that request to the Catalogue, and not exactly save the enriched data together with the request. The GET will be faster, but probably with no enriched data (vendor, name and version of the service), while a request to the Catalogue to fetch this data will be launched, updating the cache. Subsequent requests will hit the cache.

What do you think?

**Comment by jbonnet** [comment]
@felipevicens I think I found a better solution: GET the service in parallel to requesting the MANO for the instantiation, so that when the request is answered, the service metadata will already be in cache...

**Comment by jbonnet** [comment]
Wait: there's already a GET of the service (NSD) before composing the message to the MANO, so... it should be in the cache already... need to check this further, probably the `tng-gtk-common` is not yet caching the result...

**Comment by jbonnet** [comment]
Closed via #259
