### ISSUE TITLE
Integrate VIM/WIM configuration

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-sp#56]
- [ ] Request the creation of (VIM) compute-resources
- [ ] List (VIM) compute-resources (single and many)
- [ ] Request the creation of (VIM) networking-resources
- [ ] List (VIM) compute-resources (single and many)
- [ ] Request the creation of WIMs
- [ ] List WIMs (single and many)
- [ ] Attach WIM to VIM

**Comment by jbonnet** [comment]
Look at [this](https://git.cs.upb.de/5gtango/generalInfo/wikis/devel-ia-wrapper#sql-database) user story.

Table "public.vim" is

|Column     | Type | Modifiers
|---------------+------+-----------
|uuid          | text | not null
|name          | text |
|type          | text | not null
|vendor        | text | not null
|endpoint      | text | not null
|username      | text | not null
|domain        | text | not null
|configuration | text | not null
|city          | text |
|country       | text |
|pass          | text |
|authkey       | text |

**Comment by carlos-f-parada** [comment]
@carlos-f-parada @jbonnet @felipevicens @carlos-martins-marques @anapolg As some data in the DB does not make sense to be sent by the portal (e.g. IDs) and the "configuration" column is a structured value, here I have my suggestions for the API fields (strings) to the POST (add) for the different Wrappers. See my comments inline.

HEAT: (POST http:/…./heat/)
NAME, ENDPOINT, CITY(optional), COUNTRY (optional), USERNAME, PASSWORD, AUTHKEY (optional), DOMAIN, TENANT?, TENANT_EXT_NET?, TENANT_EXT_ROUTER?, TENANT_PRIV_NET?, TENANT_PRIV_NET_LENGTH?, NETWORK_VIM
Carlos: Should we specify the tenants, IDs of networks, routers, etc. (see fields with "?")? or just assume that the VIM is prepared to always use the same (standard) tenant, router, networks, etc.? Specifying this values give us flexibility but complicates the Portal and user's life (need to know that info)..

K8S:
NAME, ENDPOINT, CITY(optional), COUNTRY (optional), …
Carlos: To be decided what needs to be specified (Felipe)

OVS:  (POST http:/…./ovs/)
NAME, ENDPOINT, CITY(optional), COUNTRY (optional), USERNAME, PASSWORD, AUTHKEY (optional), DOMAIN, COMPUTE_VIM
Carlos: Merge this with the HEAT Wrapper (create both in a single API call) or keep them separate as they are now? Does it make sense 1:N relationships with HEAT or other Wrapper?

VTN: (POST http:/…./vtn/)
NAME, ENDPOINT, USERNAME, PASSWORD, AUTHKEY (optional), VIM_1, VIM_2, ? 
Carlos: Does the VTN interconnect always 2 points? or it can be multi-point (i.e. more than 2 endpoints)? If more than 2 endpoints are supported, we need to specify a list instead of just 2 VIM endpoints.

TAPI: (POST http:/…./tapi/)
NAME, ENDPOINT, USERNAME, PASSWORD, AUTHKEY (optional), …
Carlos: To be decided what else needs to be specified (Ricard)

**Comment by felipevicens** [comment]
@carlos-f-parada For HEAT, All that field with '?' needs to be filled by the Service Platform Operator so we need to configure via portal.

TENANT? = Openstack tenant
TENANT_EXT_NET? = External network ID to be used for the deployments
TENANT_EXT_ROUTER? = Router that connect the external net with new networks
TENANT_PRIV_NET? = The range where new networks will be created
TENANT_PRIV_NET_LENGTH? = The network mask of the network

**Comment by carlos-f-parada** [comment]
@jbonnet @felipevicens @carlos-f-parada Felipe, I know, they will be filled anyway.
My point is that there is a way to avoid asking for this low level (ugly) info to the user in the API and ultimately in the Portal, keeping it simple (assuming the Portal user is not very tecky). If you create a "standard" VIM, all, or at least part of the above parameters can be discovered by the IA API internally and not required to be received as parameters. For example:
- If you create a "standard" tenant e.g. "sonata", you don't need to ask this on the API/Portal
- If you create just one ext network and respective router on your VIM, you don't need to specify it anymore (the API can get it and use it)
- If you always use e.g. the 10.0.0.0/8 prefix, you don't need to specify it.

I understand that with this you lose somehow some flexibility, but you gain on simplicity. This is just a suggestion on my side, is up to us to decide what approach makes more sense.

**Comment by jbonnet** [comment]
@carlos-f-parada we might make those fields optional and fil them with those 'standard' content, but the user (either from the Portal or from the API) should always be able to change them. 'Convention over Configuration' is great... :-)

**Comment by carlos-f-parada** [comment]
@jbonnet @carlos-martins-marques @felipevicens In that case, probably the IA API need to be extended in order to allow the Portal to get info like available provide nets, routers, etc. to create a check-list for the user to pick.

**Comment by felipevicens** [comment]
Hello @carlos-f-parada it is a nice idea but I propose to have now in the portal the same configuration way we use now and not delay more an API that discovers things in the VIMs and so on. In my humble opinion, we need the configuration in the portal now, I don't think we can delay this more.

**Comment by carlos-f-parada** [comment]
@jbonnet @carlos-martins-marques @felipevicens we are starting the specification of the API and the Portal. This could be discussed in the F2F or just I wil schedule a call just the week after for that.

**Comment by jbonnet** [comment]
@carlos-f-parada can we close this issue?
